worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

path-to-words: "../res/WORDS.txt"
in-memory-storage: true

dbconnection: 'postgresql://user:password@service-postgres:5432/wordle_db-1'
