worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

path-to-words: "res/eng_words.txt"
in-memory-storage: true

dbconnection: 'postgresql://wordle_user:password@localhost:5432/'

