worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

path-to-words: "res/rus_words.txt"
in-memory-storage: true

dbconnection: 'postgresql://postgres:Mys3Cr3t@62.84.114.238:30432/wordle_db'
