worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: true

path-to-words: "../res/eng_words.txt"
in-memory-storage: true

# wordle_db is the service name + _ + filename of the db_1.sql
dbconnection: 'postgresql://testsuite@localhost:15433/wordle_db-1'
