name: Code Style
on: [ push, pull_request ]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Install cpplint
        run: pip install cpplint
      - name: Run cpplint
        run: |
          cd src
          echo "filter=-legal/copyright, -readability/todo, -build/namespaces_literals, -build/include_subdir, -build/namespaces, -runtime/references
                linelength=120" > CPPLINT.cfg
          cpplint --recursive .